from fastapi import APIRouter, HTTPException, File, UploadFile, Form, Query
from sqlmodel import Session, select
from datetime import datetime, timedelta
from collections import defaultdict
from typing import Optional, List
import os, shutil
import random
from .models import Pobuda, PobudaCreate, PobudaResponse, Statistics
from .database import engine

UPLOAD_DIR = "uploads"

LJUBLJANA_STREETS = [
    "Abramova Ulica",
    "Adamičeva Ulica",
    "Adamič-Lundrovo Nabrežje",
    "Agrokombinatska Cesta",
    "Ajdovščina",
    "Aleševa Ulica",
    "Alešovčeva Ulica",
    "Aličeva Ulica",
    "Aljaževa Ulica",
    "Ambrožev Trg",
    "Ameriška Ulica",
    "Andreaševa Ulica",
    "Andrićeva Ulica",
    "Anžurjeva Ulica",
    "Apihova Ulica",
    "Archinetova Ulica",
    "Argentinska Ulica",
    "Arharjeva Cesta",
    "Arkova Ulica",
    "Arničeva Ulica",
    "Artačeva Ulica",
    "Aškerčeva Cesta",
    "Avčinova Ulica",
    "Avgustinčičeva Ulica",
    "Avsečeva Ulica",
    "Avstrijska Ulica",
    "Avšičeva Cesta",
    "Ažbetova Ulica",
    "Ažmanova Ulica",
    "Babičeva Ulica",
    "Badjurova Ulica",
    "Bajtova Ulica",
    "Balinarska Pot",
    "Baragova Ulica",
    "Barjanska Cesta",
    "Barvarska Steza",
    "Bavdkova Ulica",
    "Baznikova Ulica",
    "Bazoviška Ulica",
    "Beblerjev Trg",
    "Beethovnova Ulica",
    "Belačeva Ulica",
    "Beljaška Ulica",
    "Belokranjska Ulica",
    "Beograjska Ulica",
    "Berčičeva Ulica",
    "Berčonova Pot",
    "Berdajsova Ulica",
    "Bergantova Ulica",
    "Bernekerjeva Ulica",
    "Bernikova Ulica",
    "Besnica",
    "Betettova Cesta",
    "Bevkova Cesta",
    "Bezenškova Ulica",
    "Bežigrad",
    "Bičevje",
    "Bilečanska Ulica",
    "Bistriška Ulica",
    "Bitenčeva Ulica",
    "Bizjakova Ulica",
    "Bizjanova Ulica",
    "Bizoviška Cesta",
    "Blasnikova Ulica",
    "Blasov Breg",
    "Blažičeva Ulica",
    "Bleiweisova Cesta",
    "Bobenčkova Ulica",
    "Bobrova Ulica",
    "Bogišićeva Ulica",
    "Bognarjeva Pot",
    "Bohinjčeva Ulica",
    "Bohoričeva Ulica",
    "Bokalova Ulica",
    "Boletova Ulica",
    "Bolgarska Ulica",
    "Borovniška Ulica",
    "Borsetova Ulica",
    "Borštnikov Trg",
    "Borutova Ulica",
    "Božičeva Ulica",
    "Brajnikova Ulica",
    "Brankova Ulica",
    "Bratinova Ulica",
    "Bratislavska Cesta",
    "Bratov Čebuljev Ulica",
    "Bratov Jakopičev Ulica",
    "Bratov Kunovarjev Ulica",
    "Bratovševa Ploščad",
    "Bravničarjeva Ulica",
    "Brdnikova Ulica",
    "Breg",
    "Bregarjeva Ulica",
    "Brejčeva Ulica",
    "Brezje Pri Lipoglavu",
    "Breznikova Ulica",
    "Brglezov Štradon",
    "Brilejeva Ulica",
    "Brnčičeva Ulica",
    "Brodarjev Trg",
    "Brodska Cesta",
    "Burnikova Ulica",
    "Cankarjev Vrh",
    "Cankarjeva Cesta",
    "Cankarjevo Nabrežje",
    "Carja Dušana Ulica",
    "Celarčeva Ulica",
    "Celestinova Ulica",
    "Celjska Ulica",
    "Celovška Cesta",
    "Cerkniška Ulica",
    "Cerkova Ulica",
    "Cerutova Ulica",
    "Cesta 13. Julija",
    "Cesta 24. Junija",
    "Cesta 25 Talcev",
    "Cesta 27. Aprila",
    "Cesta 30. Avgusta",
    "Cesta Andreja Bitenca",
    "Cesta Ceneta Štuparja",
    "Cesta Cirila Kosmača",
    "Cesta Dolomitskega Odreda",
    "Cesta Dveh Cesarjev",
    "Cesta Ii. Grupe Odredov",
    "Cesta Ljubljanske Brigade",
    "Cesta Na Bokalce",
    "Cesta Na Brdo",
    "Cesta Na Brinovec",
    "Cesta Na Brod",
    "Cesta Na Ježah",
    "Cesta Na Ključ",
    "Cesta Na Kope",
    "Cesta Na Laze",
    "Cesta Na Loko",
    "Cesta Na Mesarico",
    "Cesta Na Obrije",
    "Cesta Na Ozare",
    "Cesta Na Poljane",
    "Cesta Na Prevoje",
    "Cesta Na Rožnik",
    "Cesta Na Urh",
    "Cesta Na Vrhovce",
    "Cesta Španskih Borcev",
    "Cesta Urške Zatlerjeve",
    "Cesta V Dvor",
    "Cesta V Gameljne",
    "Cesta V Gorice",
    "Cesta V Hrastje",
    "Cesta V Hrib",
    "Cesta V Kleče",
    "Cesta V Kostanj",
    "Cesta V Kresnice",
    "Cesta V Legarico",
    "Cesta V Mestni Log",
    "Cesta V Pečale",
    "Cesta V Podboršt",
    "Cesta V Prod",
    "Cesta V Rožno Dolino",
    "Cesta V Šmartno",
    "Cesta V Zajčjo Dobravo",
    "Cesta V Zeleni Log",
    "Cesta V Zgornji Log",
    "Cesta Vstaje",
    "Chengdujska Cesta",
    "Cigaletova Ulica",
    "Cilenškova Ulica",
    "Cimermanova Ulica",
    "Cimpermanova Ulica",
    "Ciril-Metodov Trg",
    "Cizejeva Ulica",
    "Clevelandska Ulica",
    "Colnarjeva Ulica",
    "Cvetkova Ulica",
    "Cvetlična Pot",
    "Čampova Ulica",
    "Čanžekova Ulica",
    "Čapova Ulica",
    "Čargova Ulica",
    "Čebelarska Ulica",
    "Čehova Ulica",
    "Čemažarjeva Ulica",
    "Čepelnikova Ulica",
    "Čepovanska Ulica",
    "Čerinova Ulica",
    "Černetova Ulica",
    "Černigojeva Ulica",
    "Černivčeva Ulica",
    "Červanova Ulica",
    "Česnikova Ulica",
    "Češnjica",
    "Čevljarska Ulica",
    "Čižmanova Ulica",
    "Čopova Ulica",
    "Črna Pot",
    "Črna Vas",
    "Črnuška Cesta",
    "Črtomirova Ulica",
    "Čučkova Ulica",
    "Čufarjeva Ulica",
    "Dajnkova Ulica",
    "Dalmatinova Ulica",
    "Danile Kumarjeve Ulica",
    "Davčna Ulica",
    "Dečkova Ulica",
    "Dečmanova Ulica",
    "Delakova Ulica",
    "Delavska Ulica",
    "Demšarjeva Cesta",
    "Derčeva Ulica",
    "Dergančeva Ulica",
    "Dergomaška Ulica",
    "Dermotova Ulica",
    "Detelova Ulica",
    "Devinska Ulica",
    "Devova Ulica",
    "Dimičeva Ulica",
    "Divjakova Ulica",
    "Do Proge",
    "Dobrajčeva Ulica",
    "Dobrdobska Ulica",
    "Dobrunjska Cesta",
    "Dolenjska Cesta",
    "Dolgi Breg",
    "Dolgi Most",
    "Dolgo Brdo",
    "Dolharjeva Ulica",
    "Dolina",
    "Dolinarjeva Ulica",
    "Dolinškova Ulica",
    "Dolničarjeva Ulica",
    "Dolniška Cesta",
    "Dolomitska Ulica",
    "Drabosnjakova Ulica",
    "Draga",
    "Draveljska Ulica",
    "Dravska Ulica",
    "Dražgoška Ulica",
    "Drenikov Vrh",
    "Drenikova Ulica",
    "Društvena Ulica",
    "Dunajska Cesta",
    "Dvojna Ulica",
    "Dvor",
    "Dvorakova Ulica",
    "Dvorni Trg",
    "Džamijska Ulica",
    "Einspielerjeva Ulica",
    "Eipprova Ulica",
    "Ellerjeva Ulica",
    "Emonska Cesta",
    "Endliherjeva Ulica",
    "Erbežnikova Ulica",
    "Erjavčeva Cesta",
    "Fabianijeva Ulica",
    "Fajfarjeva Ulica",
    "Fani Grumove Ulica",
    "Ferberjeva Ulica",
    "Filipičeva Ulica",
    "Finžgarjeva Ulica",
    "Flajšmanova Ulica",
    "Flandrova Ulica",
    "Forsterjeva Ulica",
    "Francoska Ulica",
    "Franketova Ulica",
    "Frankopanska Ulica",
    "Frenkova Pot",
    "Freyerjeva Ulica",
    "Friškovec",
    "Funtkova Ulica",
    "Fužinska Cesta",
    "Gabrje Pri Jančah",
    "Gabrov Trg",
    "Gabrščkova Ulica",
    "Gača",
    "Galičeva Ulica",
    "Galjevica",
    "Gallusovo Nabrežje",
    "Gameljska Cesta",
    "Gasilska Cesta",
    "Gasparijeva Ulica",
    "Gašperšičeva Ulica",
    "Gerbičeva Ulica",
    "Gestrinova Ulica",
    "Glavarjeva Ulica",
    "Gledališka Pasaža",
    "Gledališka Stolba",
    "Glinška Ulica",
    "Glinškova Ploščad",
    "Globočnikova Ulica",
    "Glonarjeva Ulica",
    "Gmajnice",
    "Gobarska Pot",
    "Godeževa Ulica",
    "Gogalova Ulica",
    "Gola Loka",
    "Golarjeva Ulica",
    "Goljarjeva Pot",
    "Golouhova Ulica",
    "Gorazdova Ulica",
    "Goriška Ulica",
    "Gorjančeva Ulica",
    "Gorjupova Ulica",
    "Gorkičeva Ulica",
    "Gornji Rudnik I",
    "Gornji Rudnik Ii",
    "Gornji Rudnik Iii",
    "Gornji Rudnik Iv",
    "Gornji Trg",
    "Goropečnikova Ulica",
    "Gortanova Ulica",
    "Gosarjeva Ulica",
    "Gospodinjska Ulica",
    "Gosposka Ulica",
    "Gosposvetska Cesta",
    "Gotska Ulica",
    "Govekarjeva Ulica",
    "Gozdna Pot",
    "Grablovičeva Ulica",
    "Gradaška Ulica",
    "Gradišče",
    "Gradiškova Ulica",
    "Gradnikova Ulica",
    "Grafenauerjeva Ulica",
    "Grajska Planota",
    "Grajzerjeva Ulica",
    "Gramozna Pot",
    "Grampovčanova Ulica",
    "Grassellijeva Ulica",
    "Gregorčičeva Ulica",
    "Gregorinova Ulica",
    "Grič",
    "Grintovška Ulica",
    "Grobeljca",
    "Grobeljska Pot",
    "Groharjeva Cesta",
    "Grošljeva Ulica",
    "Groznikova Ulica",
    "Grška Ulica",
    "Grško",
    "Gruberjevo Nabrežje",
    "Grudnova Ulica",
    "Grudnovo Nabrežje",
    "Gubčeva Ulica",
    "Gunceljska Cesta",
    "Gundulićeva Ulica",
    "Gustinčarjeva Ulica",
    "Gustinčičeva Ulica",
    "Hacetova Ulica",
    "Hacquetova Ulica",
    "Hafnerjeva Ulica",
    "Hajdrihova Ulica",
    "Hauptmanca",
    "Herbersteinova Ulica",
    "Hladilniška Pot",
    "Hladnikova Cesta",
    "Hlebčeva Ulica",
    "Hodoščkova Ulica",
    "Hotimirova Ulica",
    "Hradeckega Cesta",
    "Hranilniška Ulica",
    "Hrenova Ulica",
    "Hribarjevo Nabrežje",
    "Hribernikova Ulica",
    "Hribovska Pot",
    "Hruševska Cesta",
    "Hrvaška Ulica",
    "Hrvatski Trg",
    "Hubadova Ulica",
    "Hudourniška Pot",
    "Hudovernikova Ulica",
    "Idrijska Ulica",
    "Igriška Ulica",
    "Ilešičeva Ulica",
    "Ilirska Ulica",
    "Ilovški Štradon",
    "Ingličeva Ulica",
    "Ipavčeva Ulica",
    "Italijanska Ulica",
    "Izletniška Ulica",
    "Ižanska Cesta",
    "Jadranska Ulica",
    "Jakčeva Ulica",
    "Jakhljeva Ulica",
    "Jakopičeva Ulica",
    "Jakšičeva Ulica",
    "Jalnova Ulica",
    "Jamnikarjeva Ulica",
    "Jamova Cesta",
    "Janče",
    "Janežičeva Cesta",
    "Janova Ulica",
    "Janševa Ulica",
    "Japljeva Ulica",
    "Jarčeva Ulica",
    "Jarnikova Ulica",
    "Jarše",
    "Jarška Cesta",
    "Javor",
    "Javorjev Drevored",
    "Javorškova Ulica",
    "Jazbečeva Pot",
    "Jelinčičeva Ulica",
    "Jelovškova Ulica",
    "Jenkova Ulica",
    "Jensenova Ulica",
    "Jerajeva Ulica",
    "Jerančičeva Ulica",
    "Jeranova Ulica",
    "Jesenkova Ulica",
    "Jesihov Štradon",
    "Jezerska Ulica",
    "Ježa",
    "Ježica",
    "Ježkova Ulica",
    "Joškov Štradon",
    "Jurčeva Ulica",
    "Jurčičev Trg",
    "Jurčkova Cesta",
    "Juričeva Ulica",
    "Justinova Ulica",
    "Juvanova Ulica",
    "K Reaktorju",
    "Kadilnikova Ulica",
    "Kajakaška Cesta",
    "Kajuhova Ulica",
    "Kalingerjeva Ulica",
    "Kalinova Ulica",
    "Kališnikov Trg",
    "Kaminova Ulica",
    "Kamniška Ulica",
    "Kamnogoriška Cesta",
    "Kamnoseška Ulica",
    "Kančeva Ulica",
    "Kanonijeva Cesta",
    "Kantetova Ulica",
    "Kapiteljska Ulica",
    "Kapusova Ulica",
    "Kardeljeva Ploščad",
    "Karingerjeva Ulica",
    "Karlovška Cesta",
    "Karunova Ulica",
    "Kastelčeva Ulica",
    "Kašeljska Cesta",
    "Katreževa Pot",
    "Kavadarska Cesta",
    "Kavčičeva Ulica",
    "Kavškova Ulica",
    "Kebetova Ulica",
    "Kekčeva Ulica",
    "Kermaunerjeva Ulica",
    "Kernova Cesta",
    "Kersnikova Ulica",
    "Kerševanova Ulica",
    "Keržičeva Ulica",
    "Kettejeva Ulica",
    "Kikljeva Ulica",
    "Kladezna Ulica",
    "Klančarjeva Ulica",
    "Kleče",
    "Klemenčičeva Ulica",
    "Klemenova Ulica",
    "Ključavničarska Ulica",
    "Klopčičeva Ulica",
    "Klunova Ulica",
    "Kmečka Pot",
    "Knafljev Prehod",
    "Kneza Koclja Ulica",
    "Knezov Štradon",
    "Knezova Ulica",
    "Knobleharjeva Ulica",
    "Kobetova Ulica",
    "Koblarjeva Ulica",
    "Kocenova Ulica",
    "Kocjančičeva Ulica",
    "Kocjanova Ulica",
    "Kočenska Ulica",
    "Kodrova Ulica",
    "Kogejeva Ulica",
    "Kogojeva Ulica",
    "Kogovškova Ulica",
    "Kokaljeva Ulica",
    "Kolajbova Ulica",
    "Kolarjeva Ulica",
    "Kolesarska Pot",
    "Koleševa Ulica",
    "Kolezijska Ulica",
    "Kolinska Ulica",
    "Kolmanova Ulica",
    "Kolodvorska Ulica",
    "Komacova Ulica",
    "Komanova Ulica",
    "Komenskega Ulica",
    "Kongresni Trg",
    "Kopačeva Cesta",
    "Kopališka Ulica",
    "Kopitarjeva Ulica",
    "Kopna Pot",
    "Koprska Ulica",
    "Korenčanova Ulica",
    "Koreninova Ulica",
    "Koroška Ulica",
    "Korotanska Ulica",
    "Korytkova Ulica",
    "Kosančeva Ulica",
    "Koseskega Ulica",
    "Koseška Cesta",
    "Kosijeva Ulica",
    "Kosmačeva Ulica",
    "Kosova Ulica",
    "Kosovelova Ulica",
    "Koščeva Ulica",
    "Koširjeva Ulica",
    "Kotnikova Ulica",
    "Kovačeva Ulica",
    "Kovačičeva Ulica",
    "Kovaška Ulica",
    "Kovinarska Ulica",
    "Kozarska Cesta",
    "Kozinova Ulica",
    "Kozlarjeva Pot",
    "Koželjeva Ulica",
    "Krakovska Ulica",
    "Krakovski Nasip",
    "Kraljeva Ulica",
    "Kranerjeva Ulica",
    "Kranjčeva Ulica",
    "Kraška Ulica",
    "Kratka Pot",
    "Kratka Steza",
    "Kregarjeva Ulica",
    "Krekov Trg",
    "Kreljeva Ulica",
    "Kremžarjeva Ulica",
    "Krimska Ulica",
    "Kristanova Ulica",
    "Krištofova Ulica",
    "Kriva Pot",
    "Krivec",
    "Križevniška Ulica",
    "Križna Ulica",
    "Krmčeva Ulica",
    "Krmeljeva Ulica",
    "Krojaška Ulica",
    "Kropova Ulica",
    "Krošljeva Ulica",
    "Krovska Ulica",
    "Krožna Pot",
    "Krvinova Ulica",
    "Kržičeva Ulica",
    "Kudrova Ulica",
    "Kumanovska Ulica",
    "Kumerdejeva Ulica",
    "Kumrovška Ulica",
    "Kunaverjeva Ulica",
    "Kurilniška Ulica",
    "Kurirska Ulica",
    "Kušarjeva Ulica",
    "Kuštrinova Ulica",
    "Kuzeletova Ulica",
    "Kuzmičeva Ulica",
    "Kvedrova Cesta",
    "Lahova Pot",
    "Lajovčeva Ulica",
    "Laknerjeva Ulica",
    "Lakotence",
    "Lambergarjeva Ulica",
    "Lampetova Ulica",
    "Lamutova Ulica",
    "Langusova Ulica",
    "Latinski Trg",
    "Lavričeva Ulica",
    "Lavrinova Ulica",
    "Layerjeva Ulica",
    "Lazarjeva Ulica",
    "Ledarska Ulica",
    "Legatova Ulica",
    "Lemeževa Ulica",
    "Lepi Pot",
    "Lepodvorska Ulica",
    "Leskoškova Cesta",
    "Leskovičeva Ulica",
    "Letališka Cesta",
    "Levarjeva Ulica",
    "Levčeva Ulica",
    "Levičnikova Ulica",
    "Levstikov Trg",
    "Levstikova Ulica",
    "Likozarjeva Ulica",
    "Linhartov Podhod",
    "Linhartova Cesta",
    "Lipahova Ulica",
    "Lipe",
    "Litijska Cesta",
    "Litostrojska Cesta",
    "Livada",
    "Livarska Ulica",
    "Ljubeljska Ulica",
    "Ločnikarjeva Ulica",
    "Lončarska Steza",
    "Lotričeva Ulica",
    "Lovrenčičeva Ulica",
    "Lovska Ulica",
    "Lovšetova Ulica",
    "Ložarjeva Ulica",
    "Lubejeva Ulica",
    "Luize Pesjakove Ulica",
    "Lunačkova Ulica",
    "Lužiško-Srbska Ulica",
    "Mačkov Kot",
    "Mačkova Ulica",
    "Madžarska Ulica",
    "Magajnova Ulica",
    "Magistrova Ulica",
    "Maistrova Ulica",
    "Majaronova Ulica",
    "Majde Šilčeve Ulica",
    "Majde Vrhovnikove Ulica",
    "Majorja Lavriča Ulica",
    "Makucova Ulica",
    "Mala Čolnarska Ulica",
    "Mala Ulica",
    "Mala Vas",
    "Malejeva Ulica",
    "Malenškova Ulica",
    "Maleševa Ulica",
    "Malgajeva Ulica",
    "Mali Lipoglav",
    "Mali Trg",
    "Mali Vrh Pri Prežganju",
    "Malnarjeva Ulica",
    "Malo Trebeljevo",
    "Malova Ulica",
    "Marčenkova Ulica",
    "Marentičeva Ulica",
    "Mareška Pot",
    "Mariborska Ulica",
    "Marice Kovačeve Ulica",
    "Marincljeva Ulica",
    "Marinovševa Cesta",
    "Marjekova Pot",
    "Maroltova Ulica",
    "Martina Krpana Ulica",
    "Martinčeva Ulica",
    "Martinova Pot",
    "Martinova Ulica",
    "Marušičeva Ulica",
    "Masarykova Cesta",
    "Mašera-Spasićeva Ulica",
    "Matjanova Pot",
    "Matjaževa Ulica",
    "Maurerjeva Ulica",
    "Mazijeva Ulica",
    "Mazovčeva Pot",
    "Med Hmeljniki",
    "Medarska Ulica",
    "Medenska Cesta",
    "Medno",
    "Medvedova Cesta",
    "Medveščkova Ulica",
    "Mekinčeva Ulica",
    "Melikova Ulica",
    "Menardova Ulica",
    "Mencingerjeva Ulica",
    "Merčnikova Ulica",
    "Merosodna Ulica",
    "Mesarska Cesta",
    "Mesesnelova Ulica",
    "Mestni Trg",
    "Meškova Ulica",
    "Metelkova Ulica",
    "Metliška Ulica",
    "Miheličeva Cesta",
    "Mihov Štradon",
    "Miklavčeva Ulica",
    "Miklošičeva Cesta",
    "Mikuževa Ulica",
    "Milčetova Pot",
    "Milčinskega Ulica",
    "Mire Lenardičeve Ulica",
    "Mirje",
    "Mirna Pot",
    "Mislejeva Ulica",
    "Mivka",
    "Mizarska Pot",
    "Mladinska Ulica",
    "Mlake",
    "Mlinska Pot",
    "Močilnikarjeva Ulica",
    "Močnikova Ulica",
    "Mokrška Ulica",
    "Molekova Ulica",
    "Moskovska Ulica",
    "Moškričeva Ulica",
    "Mrharjeva Ulica",
    "Mrzelova Ulica",
    "Mucherjeva Ulica",
    "Murkova Ulica",
    "Murnikova Ulica",
    "Murnova Ulica",
    "Muzejska Ulica",
    "Na Brežini",
    "Na Cvetači",
    "Na Delih",
    "Na Dolih",
    "Na Gaju",
    "Na Gmajni",
    "Na Griču",
    "Na Herši",
    "Na Jami",
    "Na Klančku",
    "Na Korošci",
    "Na Palcah",
    "Na Peči",
    "Na Požaru",
    "Na Produ",
    "Na Rojah",
    "Na Stolbi",
    "Na Straški Vrh",
    "Na Tezi",
    "Na Trati",
    "Na Žalah",
    "Nade Ovčakove Ulica",
    "Nadgoriška Cesta",
    "Nagodetova Ulica",
    "Nahlikova Ulica",
    "Nahtigalova Ulica",
    "Nanoška Ulica",
    "Nasperska Pot",
    "Nazorjeva Ulica",
    "Nedohova Ulica",
    "Neubergerjeva Ulica",
    "Njegoševa Cesta",
    "Nova Ulica",
    "Novakova Pot",
    "Novakova Ulica",
    "Nove Fužine",
    "Novi Trg",
    "Novinarska Ulica",
    "Novo Naselje",
    "Novo Polje, Cesta I",
    "Novo Polje, Cesta Ii",
    "Novo Polje, Cesta Iii",
    "Novo Polje, Cesta Iv",
    "Novo Polje, Cesta Ix",
    "Novo Polje, Cesta V",
    "Novo Polje, Cesta Vi",
    "Novo Polje, Cesta Vii",
    "Novo Polje, Cesta Viii",
    "Novo Polje, Cesta X",
    "Novo Polje, Cesta Xi",
    "Novo Polje, Cesta Xii",
    "Novo Polje, Cesta Xiii",
    "Novo Polje, Cesta Xiv",
    "Novo Polje, Cesta Xix",
    "Novo Polje, Cesta Xv",
    "Novo Polje, Cesta Xvi",
    "Novo Polje, Cesta Xvii",
    "Novo Polje, Cesta Xviii",
    "Novo Polje, Cesta Xxi",
    "Novo Polje, Cesta Xxiii",
    "Novosadska Ulica",
    "Nusdorferjeva Ulica",
    "Ob Daljnovodu",
    "Ob Dolenjski Železnici",
    "Ob Farjevcu",
    "Ob Kamniški Progi",
    "Ob Ljubljanici",
    "Ob Mejašu",
    "Ob Potoku",
    "Ob Pristanu",
    "Ob Savi",
    "Ob Sotočju",
    "Ob Studencu",
    "Ob Zdravstvenem Domu",
    "Ob Zeleni Jami",
    "Ob Zelenici",
    "Ob Železnici",
    "Ob Žici",
    "Obirska Ulica",
    "Obrežna Steza",
    "Obrije",
    "Obvozna Cesta",
    "Ocvirkova Ulica",
    "Ogrinčeva Ulica",
    "Okiškega Ulica",
    "Okrogarjeva Ulica",
    "Omahnova Ulica",
    "Omejčeva Ulica",
    "Omersova Ulica",
    "Opekarska Cesta",
    "Oražnova Ulica",
    "Orlova Ulica",
    "Osenjakova Ulica",
    "Oslavijska Ulica",
    "Osojna Pot",
    "Osterčeva Ulica",
    "Ovčakova Ulica",
    "Pahorjeva Ulica",
    "Palmejeva Ulica",
    "Pance",
    "Papirniška Pot",
    "Papirniški Trg",
    "Parmova Ulica",
    "Parmska Cesta",
    "Partizanska Ulica",
    "Pasterkova Pot",
    "Pavlovčeva Ulica",
    "Pavšičeva Ulica",
    "Pečarjeva Ulica",
    "Pečinska Ulica",
    "Pečnik",
    "Pečnikova Ulica",
    "Pegamova Ulica",
    "Perčeva Ulica",
    "Peričeva Ulica",
    "Periška Cesta",
    "Perkova Ulica",
    "Peršinova Cesta",
    "Peruzzijeva Ulica",
    "Pesarska Cesta",
    "Pestotnikova Ulica",
    "Peščena Pot",
    "Petkova Ulica",
    "Petkovškovo Nabrežje",
    "Petrčeva Ulica",
    "Petričeva Ulica",
    "Pilonova Ulica",
    "Pionirska Pot",
    "Pipanova Pot",
    "Pirnatova Ulica",
    "Pivovarniška Ulica",
    "Planinska Cesta",
    "Planinškova Ulica",
    "Plečnikov Podhod",
    "Plečnikov Trg",
    "Plemljeva Ulica",
    "Plešičeva Ulica",
    "Pleteršnikova Ulica",
    "Plevančeva Ulica",
    "Pločanska Ulica",
    "Pod Akacijami",
    "Pod Bregom",
    "Pod Bresti",
    "Pod Brezami",
    "Pod Bukvami",
    "Pod Debnim Vrhom",
    "Pod Gabri",
    "Pod Gozdom",
    "Pod Gričem",
    "Pod Hrasti",
    "Pod Hribom",
    "Pod Hruško",
    "Pod Jelšami",
    "Pod Jeseni",
    "Pod Jezom",
    "Pod Ježami",
    "Pod Kamno Gorico",
    "Pod Klancem",
    "Pod Kostanji",
    "Pod Lipami",
    "Pod Topoli",
    "Pod Trančo",
    "Pod Turnom",
    "Pod Vrbami",
    "Podgorica",
    "Podgornikova Ulica",
    "Podgorska Cesta",
    "Podgrajska Cesta",
    "Podhod Ajdovščina",
    "Podjunska Ulica",
    "Podlimbarskega Ulica",
    "Podlipoglav",
    "Podmilščakova Ulica",
    "Podmolniška Cesta",
    "Podrožniška Pot",
    "Podutiška Cesta",
    "Podvozna Pot",
    "Pogačarjev Trg",
    "Pohlinova Ulica",
    "Poklukarjeva Ulica",
    "Pokopališka Ulica",
    "Polakova Ulica",
    "Polanškova Ulica",
    "Poljanska Cesta",
    "Poljanski Nasip",
    "Polje",
    "Polje, Cesta Ii",
    "Polje, Cesta V",
    "Polje, Cesta Vi",
    "Polje, Cesta Viii",
    "Polje, Cesta X",
    "Polje, Cesta Xii",
    "Polje, Cesta Xiv",
    "Polje, Cesta Xl",
    "Polje, Cesta Xliv",
    "Polje, Cesta Xlvi",
    "Polje, Cesta Xvi",
    "Polje, Cesta Xviii",
    "Polje, Cesta Xx",
    "Polje, Cesta Xxii",
    "Polje, Cesta Xxiv",
    "Polje, Cesta Xxvi",
    "Polje, Cesta Xxviii",
    "Polje, Cesta Xxx",
    "Polje, Cesta Xxxii",
    "Polje, Cesta Xxxiv",
    "Polje, Cesta Xxxvi",
    "Polje, Cesta Xxxviii",
    "Poljedelska Ulica",
    "Poljska Pot",
    "Popovičeva Ulica",
    "Porentova Ulica",
    "Posavskega Ulica",
    "Postojnska Ulica",
    "Pot Čez Gmajno",
    "Pot Do Šole",
    "Pot Draga Jakopiča",
    "Pot Heroja Trtnika",
    "Pot Ilegalcev",
    "Pot K Igrišču",
    "Pot K Izviru",
    "Pot K Ribniku",
    "Pot K Savi",
    "Pot K Sejmišču",
    "Pot K Skakalnici",
    "Pot K Studencu",
    "Pot Na Breje",
    "Pot Na Drenikov Vrh",
    "Pot Na Fužine",
    "Pot Na Golovec",
    "Pot Na Goro",
    "Pot Na Gradišče",
    "Pot Na Grič",
    "Pot Na Hreše",
    "Pot Na Labar",
    "Pot Na Mah",
    "Pot Na Most",
    "Pot Na Orle",
    "Pot Na Rakovo Jelšo",
    "Pot Na Visoko",
    "Pot Na Zduše",
    "Pot Rdečega Križa",
    "Pot Sodarjev",
    "Pot V Boršt",
    "Pot V Čeželj",
    "Pot V Dolino",
    "Pot V Goričico",
    "Pot V Hrastovec",
    "Pot V Hribec",
    "Pot V Mejah",
    "Pot V Mlake",
    "Pot V Podgorje",
    "Pot V Smrečje",
    "Pot V Zeleni Gaj",
    "Pot Za Brdom",
    "Pot Za Razori",
    "Potočnikova Ulica",
    "Potokarjeva Ulica",
    "Potrčeva Ulica",
    "Povšetova Ulica",
    "Praprotnikova Ulica",
    "Prašnikarjeva Ulica",
    "Praznikova Ulica",
    "Pražakova Ulica",
    "Prečna Ulica",
    "Pred Savljami",
    "Predjamska Cesta",
    "Pregljeva Ulica",
    "Preglov Trg",
    "Prekmurska Ulica",
    "Prelčeva Ulica",
    "Preloge",
    "Prelovčeva Ulica",
    "Premrlova Ulica",
    "Preradovićeva Ulica",
    "Preserska Ulica",
    "Presetnikova Ulica",
    "Prešernov Trg",
    "Prešernova Cesta",
    "Pretnarjeva Ulica",
    "Prežganje",
    "Prežihova Ulica",
    "Pri Borštu",
    "Pri Malem Kamnu",
    "Pri Mostiščarjih",
    "Pri Velikem Kamnu",
    "Pribinova Ulica",
    "Prijateljeva Ulica",
    "Primorska Ulica",
    "Primožičeva Ulica",
    "Prinčičeva Ulica",
    "Prisojna Ulica",
    "Prištinska Ulica",
    "Privoz",
    "Privškova Ulica",
    "Proletarska Cesta",
    "Prule",
    "Prušnikova Ulica",
    "Prvomajska Ulica",
    "Pržanjska Ulica",
    "Pšatnik",
    "Pšatska Pot",
    "Ptujska Ulica",
    "Pugljeva Ulica",
    "Puharjeva Ulica",
    "Puhova Ulica",
    "Puhtejeva Ulica",
    "Pustovrhova Ulica",
    "Puterlejeva Ulica",
    "Putrihova Ulica",
    "Raičeva Ulica",
    "Rakarska Ulica",
    "Rakovniška Ulica",
    "Rakuševa Ulica",
    "Ramovševa Ulica",
    "Rašica",
    "Rašiška Ulica",
    "Ravbarjeva Ulica",
    "Ravna Pot",
    "Ravnikova Ulica",
    "Ravno Brdo",
    "Razdevškova Ulica",
    "Reber",
    "Reboljeva Ulica",
    "Rečna Ulica",
    "Redelonghijeva Ulica",
    "Regentova Cesta",
    "Repče",
    "Resljeva Cesta",
    "Reška Ulica",
    "Rezijanska Ulica",
    "Ribičičeva Ulica",
    "Ribji Trg",
    "Ribniška Ulica",
    "Riharjeva Ulica",
    "Rimska Cesta",
    "Rjava Cesta",
    "Robbova Ulica",
    "Robičeva Ulica",
    "Rocenska Ulica",
    "Rodičeva Ulica",
    "Rojčeva Ulica",
    "Romavhova Ulica",
    "Rosna Pot",
    "Roška Cesta",
    "Rotarjeva Ulica",
    "Rovšnikova Ulica",
    "Rozmanova Ulica",
    "Rožančeva Cesta",
    "Rožanska Ulica",
    "Rožičeva Ulica",
    "Rožna Dolina, Cesta I",
    "Rožna Dolina, Cesta Ii",
    "Rožna Dolina, Cesta Iii",
    "Rožna Dolina, Cesta Iv",
    "Rožna Dolina, Cesta Ix",
    "Rožna Dolina, Cesta V",
    "Rožna Dolina, Cesta Vi",
    "Rožna Dolina, Cesta Vii",
    "Rožna Dolina, Cesta Viii",
    "Rožna Dolina, Cesta X",
    "Rožna Dolina, Cesta Xi",
    "Rožna Dolina, Cesta Xii",
    "Rožna Dolina, Cesta Xiii",
    "Rožna Dolina, Cesta Xix",
    "Rožna Dolina, Cesta Xv",
    "Rožna Dolina, Cesta Xvii",
    "Rožna Dolina, Cesta Xxi",
    "Rožna Ulica",
    "Rudnik I",
    "Rudnik Ii",
    "Rudnik Iii",
    "Runkova Ulica",
    "Rusjanov Trg",
    "Ruska Ulica",
    "Rutarjeva Ulica",
    "Sadinja Vas",
    "Sajovčeva Ulica",
    "Salendrova Ulica",
    "Samova Ulica",
    "Saškova Ulica",
    "Sattnerjeva Ulica",
    "Saveljska Cesta",
    "Savinova Ulica",
    "Savinškova Ulica",
    "Savlje",
    "Savska Cesta",
    "Scopolijeva Ulica",
    "Sedejeva Ulica",
    "Selanov Trg",
    "Selanova Ulica",
    "Seliškarjeva Ulica",
    "Selo Pri Pancah",
    "Setnikarjeva Ulica",
    "Seunigova Ulica",
    "Simončičeva Ulica",
    "Simonitijeva Ulica",
    "Siva Pot",
    "Skapinova Ulica",
    "Sketova Ulica",
    "Skopčeva Ulica",
    "Skopska Ulica",
    "Skrbinškova Ulica",
    "Slape",
    "Slapnikova Ulica",
    "Slavčja Ulica",
    "Slodnjakova Ulica",
    "Slomškova Ulica",
    "Slovenčeva Ulica",
    "Slovenska Cesta",
    "Smerdujeva Ulica",
    "Smoletova Ulica",
    "Smrekarjeva Ulica",
    "Smrtnikova Ulica",
    "Sneberska Cesta",
    "Snebersko Nabrežje",
    "Snežniška Ulica",
    "Snojeva Ulica",
    "Sodarska Steza",
    "Sojerjeva Ulica",
    "Sončna Pot",
    "Sostrska Cesta",
    "Soška Ulica",
    "Soteska",
    "Soteška Pot",
    "Soussenska Ulica",
    "Sovretova Ulica",
    "Splitska Ulica",
    "Spodnje Gameljne",
    "Spodnji Rudnik I",
    "Spodnji Rudnik Ii",
    "Spodnji Rudnik Iii",
    "Spodnji Rudnik Iv",
    "Spodnji Rudnik V",
    "Spomeniška Pot",
    "Srebrničeva Ulica",
    "Središka Ulica",
    "Srednja Pot",
    "Srednje Gameljne",
    "Stadionska Ulica",
    "Stanežiče",
    "Staničeva Ulica",
    "Stantetova Ulica",
    "Stara Ježica",
    "Stara Slovenska Ulica",
    "Stare Črnuče",
    "Staretova Ulica",
    "Stari Trg",
    "Stegne",
    "Steletova Ulica",
    "Sternadova Ulica",
    "Sternenova Ulica",
    "Stiška Ulica",
    "Stolpniška Ulica",
    "Stoženska Ulica",
    "Stožice",
    "Stranska Pot",
    "Stražarjeva Ulica",
    "Streliška Ulica",
    "Stritarjeva Ulica",
    "Strmec",
    "Strmeckijeva Ulica",
    "Strmi Pot",
    "Strniševa Cesta",
    "Strojeva Ulica",
    "Strossmayerjeva Ulica",
    "Strugarska Ulica",
    "Studenec",
    "Suhadolčanova Ulica",
    "Sulčja Ulica",
    "Svetčeva Ulica",
    "Svetosavska Ulica",
    "Šarhova Ulica",
    "Šentjakob",
    "Šentpavel",
    "Šentviška Ulica",
    "Šercerjeva Ulica",
    "Šerkova Ulica",
    "Šestova Ulica",
    "Šibeniška Ulica",
    "Šifrerjeva Ulica",
    "Šinkov Štradon",
    "Šišenska Cesta",
    "Šivičeva Ulica",
    "Škerjančeva Ulica",
    "Škerljeva Ulica",
    "Škofova Ulica",
    "Škrabčeva Ulica",
    "Šlajmerjeva Ulica",
    "Šlandrova Ulica",
    "Šlosarjeva Ulica",
    "Šmarna Gora",
    "Šmarnogorska Pot",
    "Šmartinska Cesta",
    "Šmartno",
    "Španova Pot",
    "Španska Ulica",
    "Športna Ulica",
    "Štajerska Cesta",
    "Štebijeva Cesta",
    "Štefančeva Ulica",
    "Štefanova Ulica",
    "Štembalova Ulica",
    "Štepanjska Cesta",
    "Štepanjsko Nabrežje",
    "Štihova Ulica",
    "Štirnova Ulica",
    "Štrekljeva Ulica",
    "Štrukljeva Ulica",
    "Študentovska Ulica",
    "Štukljeva Cesta",
    "Štula",
    "Štularjeva Ulica",
    "Šturmova Ulica",
    "Šubičeva Ulica",
    "Šumarjeva Ulica",
    "Švabićeva Ulica",
    "Švarova Ulica",
    "Švedska Ulica",
    "Švegljeva Cesta",
    "Tabor",
    "Taborska Cesta",
    "Tacenska Cesta",
    "Tavčarjeva Ulica",
    "Tbilisijska Ulica",
    "Tehnološki Park",
    "Tesarska Ulica",
    "Teslova Ulica",
    "Tesna Ulica",
    "Tesovnikova Ulica",
    "Thumova Ulica",
    "Tiha Ulica",
    "Tiranova Ulica",
    "Tischlerjeva Ulica",
    "Tisnikarjeva Ulica",
    "Tivolska Cesta",
    "Tkalska Ulica",
    "Tobačna Ulica",
    "Tolminska Ulica",
    "Tolstojeva Ulica",
    "Tomačevo",
    "Tomačevska Cesta",
    "Tomažičeva Ulica",
    "Tomčeva Ulica",
    "Tometova Ulica",
    "Tominškova Ulica",
    "Tomišeljska Ulica",
    "Tomšičeva Ulica",
    "Toplarniška Ulica",
    "Topniška Ulica",
    "Torkarjeva Ulica",
    "Toško Čelo",
    "Tovarniška Ulica",
    "Tratnikova Ulica",
    "Travniška Ulica",
    "Trbeže",
    "Trdinova Ulica",
    "Trebinjska Ulica",
    "Trebušakova Ulica",
    "Trg 9. Maja",
    "Trg Francoske Revolucije",
    "Trg Komandanta Staneta",
    "Trg Mladih",
    "Trg Mladinskih Delov. Brigad",
    "Trg Osvobodilne Fronte",
    "Trg Prekomorskih Brigad",
    "Trg Republike",
    "Triglavska Ulica",
    "Trinkova Ulica",
    "Trnovčeva Ulica",
    "Trnovska Ulica",
    "Trnovski Pristan",
    "Trpinčeva Ulica",
    "Trstenjakova Ulica",
    "Trtnikova Ulica",
    "Trubarjeva Cesta",
    "Tržaška Cesta",
    "Tržna Ulica",
    "Tugomerjeva Ulica",
    "Tuji Grm",
    "Turjaška Ulica",
    "Turnerjeva Ulica",
    "Udvančeva Ulica",
    "Ukmarjeva Ulica",
    "Ulica 15. Aprila",
    "Ulica 15. Maja",
    "Ulica 24. Avgusta",
    "Ulica 28. Maja",
    "Ulica 9. Junija",
    "Ulica Aktivistov",
    "Ulica Alme Sodnik",
    "Ulica Alojza Kajina",
    "Ulica Ambrožiča Novljana",
    "Ulica Andreja Kumarja",
    "Ulica Ane Ziherlove",
    "Ulica Angelce Ocepkove",
    "Ulica Angele Ljubičeve",
    "Ulica Angele Vode",
    "Ulica Bena Zupančiča",
    "Ulica Borca Petra",
    "Ulica Borcev Za Severno Mejo",
    "Ulica Bratov Babnik",
    "Ulica Bratov Bezlajev",
    "Ulica Bratov Blanč",
    "Ulica Bratov Jančar",
    "Ulica Bratov Knapič",
    "Ulica Bratov Komel",
    "Ulica Bratov Kraljič",
    "Ulica Bratov Martinec",
    "Ulica Bratov Miklič",
    "Ulica Bratov Novak",
    "Ulica Bratov Rozmanov",
    "Ulica Bratov Škofov",
    "Ulica Bratov Tuma",
    "Ulica Bratov Učakar",
    "Ulica Bratov Židan",
    "Ulica Carla Benza",
    "Ulica Dušana Kraigherja",
    "Ulica Ekvorna",
    "Ulica Ernesta Kramerja",
    "Ulica Ferda Kozaka",
    "Ulica Franca Mlakarja",
    "Ulica Franca Nebca",
    "Ulica Franje Koširjeve",
    "Ulica Gledališča Btc",
    "Ulica Goce Delčeva",
    "Ulica Gradnikove Brigade",
    "Ulica Gubčeve Brigade",
    "Ulica Hermana Potočnika",
    "Ulica Iga Grudna",
    "Ulica Ivana Roba",
    "Ulica Ivane Kobilce",
    "Ulica Ivanke Kožuh",
    "Ulica Ivice Pirjevčeve",
    "Ulica Jana Husa",
    "Ulica Janeza Pavla Ii.",
    "Ulica Janeza Rožiča",
    "Ulica Josipine Turnograjske",
    "Ulica Jožeta Jame",
    "Ulica Jožeta Japlja",
    "Ulica Jožeta Mirtiča",
    "Ulica Jožeta Štruklja",
    "Ulica Juša Kozaka",
    "Ulica Konrada Babnika",
    "Ulica Koroškega Bataljona",
    "Ulica Lili Novy",
    "Ulica Lizike Jančarjeve",
    "Ulica Lojzeta Spacala",
    "Ulica Lojzke Štebijeve",
    "Ulica Lovre Klemenčiča",
    "Ulica Malči Beličeve",
    "Ulica Manice Komanove",
    "Ulica Marije Drakslerjeve",
    "Ulica Marije Hvaličeve",
    "Ulica Marije Mlinar",
    "Ulica Marje Boršnikove",
    "Ulica Marka Šlajmerja",
    "Ulica Metoda Mikuža",
    "Ulica Milana Majcna",
    "Ulica Milke Kerinove",
    "Ulica Minke Bobnar",
    "Ulica Mire Miheličeve",
    "Ulica Mirka Jurce",
    "Ulica Mirka Tomšiča",
    "Ulica Miroslava Kokolja",
    "Ulica Miroslava Turka",
    "Ulica Miru",
    "Ulica Molniške Čete",
    "Ulica Na Grad",
    "Ulica Nade Čamernikove",
    "Ulica Nadgoriških Borcev",
    "Ulica Olge Mohorjeve",
    "Ulica Padlih Borcev",
    "Ulica Pariške Komune",
    "Ulica Pavle Jeromnove",
    "Ulica Pohorskega Bataljona",
    "Ulica Polonce Čude",
    "Ulica Pregnancev",
    "Ulica Prvoborcev",
    "Ulica Rezke Dragarjeve",
    "Ulica Rozke Usenik",
    "Ulica Rudolfa Janežiča",
    "Ulica Staneta Severja",
    "Ulica Stare Pravde",
    "Ulica Štefke Zbašnikove",
    "Ulica Talcev",
    "Ulica Tomšičeve Brigade",
    "Ulica Tončke Čečeve",
    "Ulica V Kokovšek",
    "Ulica Vida Khisla",
    "Ulica Vide Janežičeve",
    "Ulica Vide Pregarčeve",
    "Ulica Vladimirja Trampuža",
    "Ulica Za Travniki",
    "Ulica Zore Majcnove",
    "Ulica Zore Ragancinove",
    "Ulica Žanke Erjavec",
    "Ulica Željka Tonija",
    "Uraničeva Ulica",
    "Uršičev Štradon",
    "Usnjarska Ulica",
    "V Češnjico",
    "V Dolini",
    "V Dovjež",
    "V Karlovce",
    "V Karlovce",
    "V Kladeh",
    "V Murglah",
    "V Sige",
    "V Toplice",
    "V Varde",
    "V Zalar",
    "Vagajeva Ulica",
    "Valjavčeva Ulica",
    "Valjhunova Ulica",
    "Valvasorjeva Ulica",
    "Vandotova Ulica",
    "Vaška Pot",
    "Vavpotičeva Ulica",
    "Večna Pot",
    "Vegova Ulica",
    "Velebitska Ulica",
    "Velika Čolnarska Ulica",
    "Veliki Lipoglav",
    "Veliki Štradon",
    "Veliko Trebeljevo",
    "Velikovška Ulica",
    "Velnarjeva Ulica",
    "Verdnikova Ulica",
    "Verovškova Ulica",
    "Veršičeva Ulica",
    "Veselova Ulica",
    "Vevška Cesta",
    "Videmska Ulica",
    "Vidergarjeva Ulica",
    "Vidičeva Ulica",
    "Vidmarjeva Ulica",
    "Vidovdanska Cesta",
    "Vilharjev Podhod",
    "Vilharjeva Cesta",
    "Vinčarjeva Ulica",
    "Vinterca",
    "Vipavska Ulica",
    "Vipotnikova Ulica",
    "Viška Cesta",
    "Višnjevarjeva Ulica",
    "Vižmarska Pot",
    "Vnajnarje",
    "Vodmatska Ulica",
    "Vodna Steza",
    "Vodnikov Trg",
    "Vodnikova Cesta",
    "Vodnikovo Naselje",
    "Vodovodna Cesta",
    "Voduškova Ulica",
    "Vogelna Ulica",
    "Vojkova Cesta",
    "Volaričeva Ulica",
    "Volarjev Štradon",
    "Volavlje",
    "Vošnjakova Ulica",
    "Vožarski Pot",
    "Vranja Pot",
    "Vrazov Trg",
    "Vrbovec",
    "Vrbska Ulica",
    "Vregova Ulica",
    "Vrhovci, Cesta I",
    "Vrhovci, Cesta Ii",
    "Vrhovci, Cesta Iii",
    "Vrhovci, Cesta Iv",
    "Vrhovci, Cesta Ix",
    "Vrhovci, Cesta V",
    "Vrhovci, Cesta Vi",
    "Vrhovci, Cesta Viii",
    "Vrhovci, Cesta X",
    "Vrhovci, Cesta Xi",
    "Vrhovci, Cesta Xii",
    "Vrhovci, Cesta Xiii",
    "Vrhovci, Cesta Xiv",
    "Vrhovci, Cesta Xix",
    "Vrhovci, Cesta Xv",
    "Vrhovci, Cesta Xvi",
    "Vrhovci, Cesta Xvii",
    "Vrhovci, Cesta Xviii",
    "Vrhovci, Cesta Xx",
    "Vrhovci, Cesta Xxi",
    "Vrhovci, Cesta Xxii",
    "Vrhovci, Cesta Xxvi",
    "Vrhovci, Cesta Xxviii",
    "Vrhovci, Cesta Xxx",
    "Vrhovci, Cesta Xxxii",
    "Vrhovčeva Ulica",
    "Vrhovnikova Ulica",
    "Vrščajeva Ulica",
    "Vrtača",
    "Vrtna Ulica",
    "Vrtnarska Cesta",
    "Vulčeva Ulica",
    "Vurnikova Ulica",
    "Vzajemna Ulica",
    "Windischerjeva Ulica",
    "Wolfova Ulica",
    "Za Čreslom",
    "Za Garažami",
    "Za Gasilskim Domom",
    "Za Gradom",
    "Za Krajem",
    "Za Opekarno",
    "Za Partizanskim Domom",
    "Za Progo",
    "Za Vasjo",
    "Zabretova Ulica",
    "Zadnikarjeva Ulica",
    "Zadobrovška Cesta",
    "Zadružna Ulica",
    "Zagradišče",
    "Zagrebška Ulica",
    "Zajčeva Pot",
    "Zajčevi Dvori",
    "Zakotnikova Ulica",
    "Zakrajškova Ulica",
    "Zalaznikova Ulica",
    "Zaletelova Ulica",
    "Zaloška Cesta",
    "Zapuška Cesta",
    "Zarnikova Ulica",
    "Zasavska Cesta",
    "Zavetiška Ulica",
    "Zavoglje",
    "Završje",
    "Zbašnikova Ulica",
    "Zdešarjeva Cesta",
    "Zdravstvena Pot",
    "Zelena Pot",
    "Zelenova Ulica",
    "Zeljarska Ulica",
    "Zemljemerska Ulica",
    "Zevnikova Ulica",
    "Zgornja Besnica",
    "Zgornje Gameljne",
    "Ziherlova Ulica",
    "Ziljska Ulica",
    "Zlatek",
    "Znamenjska Ulica",
    "Zofke Kvedrove Ulica",
    "Zoisova Cesta",
    "Zoletova Ulica",
    "Zupanova Ulica",
    "Zvezda",
    "Zvezdarska Ulica",
    "Zvezna Ulica",
    "Zvonarska Ulica",
    "Žabarjeva Ulica",
    "Žabja Ulica",
    "Žabjak",
    "Žalska Ulica",
    "Žaucerjeva Ulica",
    "Žebretova Ulica",
    "Žeje",
    "Železna Cesta",
    "Železnikarjeva Ulica",
    "Žerjalova Ulica",
    "Žibertova Ulica",
    "Židankova Ulica",
    "Židovska Steza",
    "Židovska Ulica",
    "Žigonova Ulica",
    "Živaličeva Ulica",
    "Živinozdravska Ulica",
    "Žolgerjeva Ulica",
    "Žorgova Ulica",
    "Župančičeva Ulica"
]

LJUBLJANA_LOCATIONS = [
    "Ljubljana Center", "Bežigrad", "Šiška", "Vič", "Moste",
    "Sostro", "Šentvid", "Rožnik", "Trnovo", "Polje"
]

RANDOM_POBUDE_DATA = [
    
    {"title": "Broken sidewalk on Prešernova cesta", "description": "Large hole in sidewalk causing safety hazard", "category": "Ceste", "location": "Ljubljana Center", "status": "v obravnavi"},
    {"title": "Street light not working on Miklošičeva", "description": "Dark area at night, safety concern", "category": "Ceste", "location": "Ljubljana Center", "status": "v obravnavi"},
    {"title": "Damaged road surface on Celovška cesta", "description": "Potholes causing traffic issues", "category": "Ceste", "location": "Bežigrad", "status": "v obravnavi"},
    {"title": "Broken bench in Tivoli Park", "description": "Bench needs repair for visitors", "category": "Parki in zelenice", "location": "Rožnik", "status": "v obravnavi"},
    {"title": "Damaged bus stop shelter", "description": "Glass broken, needs replacement", "category": "Avtobusna postajališča", "location": "Šiška", "status": "v obravnavi"},
    {"title": "Broken water fountain", "description": "Fountain not working in park", "category": "Parki in zelenice", "location": "Trnovo", "status": "v obravnavi"},
    {"title": "Damaged playground equipment", "description": "Safety issue for children", "category": "Športne površine", "location": "Vič", "status": "v obravnavi"},
    {"title": "Broken street sign", "description": "Sign knocked down by vehicle", "category": "Ceste", "location": "Moste", "status": "v obravnavi"},
    {"title": "Damaged bike rack", "description": "Rack bent, unusable", "category": "Kolesarske poti", "location": "Sostro", "status": "v obravnavi"},
    {"title": "Broken trash bin", "description": "Bin damaged, needs replacement", "category": "Razno", "location": "Šentvid", "status": "v obravnavi"},
    {"title": "Damaged pedestrian crossing", "description": "Crossing lights not working", "category": "Pešpoti in pločniki", "location": "Polje", "status": "v obravnavi"},
    {"title": "Broken public toilet", "description": "Toilet out of order", "category": "Razno", "location": "Ljubljana Center", "status": "v obravnavi"},
    {"title": "Damaged bike path", "description": "Path surface damaged", "category": "Kolesarske poti", "location": "Bežigrad", "status": "v obravnavi"},
    {"title": "Broken street furniture", "description": "Table damaged in park", "category": "Parki in zelenice", "location": "Rožnik", "status": "v obravnavi"},
    {"title": "Damaged public art", "description": "Sculpture needs repair", "category": "Kultura", "location": "Šiška", "status": "v obravnavi"},
    {"title": "Broken drainage system", "description": "Water pooling on street", "category": "Ceste", "location": "Vič", "status": "v obravnavi"},
    {"title": "Damaged street curb", "description": "Curb broken, tripping hazard", "category": "Ceste", "location": "Moste", "status": "v obravnavi"},
    {"title": "Broken traffic barrier", "description": "Barrier damaged by accident", "category": "Ceste", "location": "Sostro", "status": "v obravnavi"},
    {"title": "Damaged bus shelter glass", "description": "Glass shattered, dangerous", "category": "Avtobusna postajališča", "location": "Šentvid", "status": "v obravnavi"},
    {"title": "Broken street lamp post", "description": "Lamp post leaning dangerously", "category": "Ceste", "location": "Polje", "status": "v obravnavi"},
    {"title": "Damaged bike lane marking", "description": "Lane markings faded", "category": "Kolesarske poti", "location": "Ljubljana Center", "status": "v obravnavi"},
    {"title": "Broken park gate", "description": "Gate not closing properly", "category": "Parki in zelenice", "location": "Bežigrad", "status": "v obravnavi"},
    {"title": "Damaged sidewalk tiles", "description": "Tiles loose and broken", "category": "Pešpoti in pločniki", "location": "Rožnik", "status": "v obravnavi"},
    {"title": "Broken street name sign", "description": "Sign missing letters", "category": "Ceste", "location": "Šiška", "status": "v obravnavi"},
    {"title": "Damaged public bench", "description": "Bench slats broken", "category": "Parki in zelenice", "location": "Vič", "status": "v obravnavi"},
    {"title": "Broken water meter cover", "description": "Cover missing, safety hazard", "category": "Vodovod", "location": "Moste", "status": "v obravnavi"},
    {"title": "Damaged street tree guard", "description": "Tree guard damaged", "category": "Drevesa, rastje in zelene površine", "location": "Sostro", "status": "v obravnavi"},
    {"title": "Broken bus stop sign", "description": "Sign knocked over", "category": "Avtobusna postajališča", "location": "Šentvid", "status": "v obravnavi"},
    {"title": "Damaged pedestrian bridge", "description": "Bridge railing loose", "category": "Pešpoti in pločniki", "location": "Polje", "status": "v obravnavi"},
    {"title": "Broken street drain cover", "description": "Cover cracked, dangerous", "category": "Ceste", "location": "Ljubljana Center", "status": "v obravnavi"},
    {"title": "Damaged bike path barrier", "description": "Barrier broken", "category": "Kolesarske poti", "location": "Bežigrad", "status": "v obravnavi"},
    {"title": "Broken park fence", "description": "Fence section missing", "category": "Parki in zelenice", "location": "Rožnik", "status": "v obravnavi"},
    {"title": "Damaged street light pole", "description": "Pole bent, unsafe", "category": "Ceste", "location": "Šiška", "status": "v obravnavi"},
    {"title": "Broken public trash can", "description": "Can lid broken", "category": "Razno", "location": "Vič", "status": "v obravnavi"},
    {"title": "Damaged sidewalk ramp", "description": "Ramp surface damaged", "category": "Pešpoti in pločniki", "location": "Moste", "status": "v obravnavi"},
    {"title": "Broken street tree", "description": "Tree fallen, blocking path", "category": "Drevesa, rastje in zelene površine", "location": "Sostro", "status": "v obravnavi"},
    {"title": "Damaged bus stop bench", "description": "Bench seat broken", "category": "Avtobusna postajališča", "location": "Šentvid", "status": "v obravnavi"},
    {"title": "Broken street sign post", "description": "Post bent, sign hanging", "category": "Ceste", "location": "Polje", "status": "v obravnavi"},
    {"title": "Damaged bike rack bolts", "description": "Bolts loose, rack unstable", "category": "Kolesarske poti", "location": "Ljubljana Center", "status": "v obravnavi"},
    {"title": "Broken park water tap", "description": "Tap leaking, wasting water", "category": "Vodovod", "location": "Bežigrad", "status": "v obravnavi"},
    {"title": "Damaged street gutter", "description": "Gutter clogged, flooding", "category": "Ceste", "location": "Rožnik", "status": "v obravnavi"},
    {"title": "Broken public toilet door", "description": "Door lock broken", "category": "Razno", "location": "Šiška", "status": "v obravnavi"},
    {"title": "Damaged street corner mirror", "description": "Mirror cracked, unsafe", "category": "Ceste", "location": "Vič", "status": "v obravnavi"},
    {"title": "Broken bike path surface", "description": "Surface cracked and uneven", "category": "Kolesarske poti", "location": "Moste", "status": "v obravnavi"},
    {"title": "Damaged street tree roots", "description": "Roots lifting sidewalk", "category": "Drevesa, rastje in zelene površine", "location": "Sostro", "status": "v obravnavi"},
    {"title": "Broken bus stop roof", "description": "Roof leaking", "category": "Avtobusna postajališča", "location": "Šentvid", "status": "v obravnavi"},
    {"title": "Damaged street light cover", "description": "Cover missing, exposed wiring", "category": "Ceste", "location": "Polje", "status": "v obravnavi"},
    
    
    {"title": "Bus schedule issues on route 1", "description": "Buses frequently late", "category": "LPP", "location": "Ljubljana Center", "status": "odgovorjeno"},
    {"title": "Parking problems in city center", "description": "No available parking spaces", "category": "Mirujoči promet", "location": "Ljubljana Center", "status": "v obravnavi"},
    {"title": "Bike lane blocked by construction", "description": "Cyclists forced onto road", "category": "Kolesarske poti", "location": "Bežigrad", "status": "odgovorjeno"},
    {"title": "Traffic light timing issues", "description": "Lights too short for pedestrians", "category": "Ceste", "location": "Šiška", "status": "v obravnavi"},
    {"title": "Bus stop accessibility", "description": "No ramp for wheelchair users", "category": "Avtobusna postajališča", "location": "Vič", "status": "odgovorjeno"},
    {"title": "Bike theft prevention needed", "description": "More secure bike racks", "category": "Kolesarske poti", "location": "Moste", "status": "v obravnavi"},
    {"title": "Public transport frequency", "description": "More buses needed during peak hours", "category": "LPP", "location": "Sostro", "status": "odgovorjeno"},
    {"title": "Pedestrian crossing safety", "description": "Crossing too dangerous", "category": "Pešpoti in pločniki", "location": "Šentvid", "status": "v obravnavi"},
    {"title": "Bike path maintenance", "description": "Path needs cleaning", "category": "Kolesarske poti", "location": "Polje", "status": "odgovorjeno"},
    {"title": "Bus route optimization", "description": "Route changes needed", "category": "LPP", "location": "Rožnik", "status": "v obravnavi"},
    {"title": "Traffic congestion on main street", "description": "Heavy traffic during rush hour", "category": "Ceste", "location": "Ljubljana Center", "status": "odgovorjeno"},
    {"title": "Bike lane width too narrow", "description": "Lane too narrow for safe cycling", "category": "Kolesarske poti", "location": "Bežigrad", "status": "v obravnavi"},
    {"title": "Bus stop location inconvenient", "description": "Stop too far from destination", "category": "Avtobusna postajališča", "location": "Šiška", "status": "odgovorjeno"},
    {"title": "Traffic signal malfunction", "description": "Signal stuck on red", "category": "Ceste", "location": "Vič", "status": "v obravnavi"},
    {"title": "Bike path connection missing", "description": "Gap in bike network", "category": "Kolesarske poti", "location": "Moste", "status": "odgovorjeno"},
    {"title": "Public transport reliability", "description": "Buses often delayed", "category": "LPP", "location": "Sostro", "status": "v obravnavi"},
    {"title": "Pedestrian zone enforcement", "description": "Cars driving in pedestrian area", "category": "Javni red in mir", "location": "Šentvid", "status": "odgovorjeno"},
    {"title": "Bike sharing station empty", "description": "No bikes available", "category": "Kolesarske poti", "location": "Polje", "status": "v obravnavi"},
    {"title": "Bus driver behavior", "description": "Aggressive driving reported", "category": "LPP", "location": "Rožnik", "status": "odgovorjeno"},
    {"title": "Traffic calming measures needed", "description": "Speed bumps required", "category": "Umiritev prometa in varnost", "location": "Ljubljana Center", "status": "v obravnavi"},
    {"title": "Bike lane surface quality", "description": "Surface rough and bumpy", "category": "Kolesarske poti", "location": "Bežigrad", "status": "odgovorjeno"},
    {"title": "Public transport information", "description": "Real-time updates needed", "category": "LPP", "location": "Šiška", "status": "v obravnavi"},
    {"title": "Pedestrian bridge maintenance", "description": "Bridge needs repair", "category": "Pešpoti in pločniki", "location": "Vič", "status": "odgovorjeno"},
    {"title": "Bike path lighting", "description": "Path too dark at night", "category": "Kolesarske poti", "location": "Moste", "status": "v obravnavi"},
    {"title": "Bus stop shelter design", "description": "Shelter not weatherproof", "category": "Avtobusna postajališča", "location": "Sostro", "status": "odgovorjeno"},
    {"title": "Traffic flow optimization", "description": "Traffic patterns inefficient", "category": "Ceste", "location": "Šentvid", "status": "odgovorjeno"},
    {"title": "Bike lane intersection safety", "description": "Dangerous intersection", "category": "Kolesarske poti", "location": "Polje", "status": "v obravnavi"},
    {"title": "Public transport accessibility", "description": "Low-floor buses needed", "category": "LPP", "location": "Rožnik", "status": "odgovorjeno"},
    {"title": "Pedestrian walkway width", "description": "Sidewalk too narrow", "category": "Pešpoti in pločniki", "location": "Ljubljana Center", "status": "v obravnavi"},
    {"title": "Bike path winter maintenance", "description": "Path not cleared of snow", "category": "Kolesarske poti", "location": "Bežigrad", "status": "odgovorjeno"},
    {"title": "Bus route coverage gaps", "description": "Areas not served by buses", "category": "LPP", "location": "Šiška", "status": "v obravnavi"},
    {"title": "Traffic sign visibility", "description": "Signs hidden by vegetation", "category": "Ceste", "location": "Vič", "status": "odgovorjeno"},
    {"title": "Bike lane continuity", "description": "Lane ends abruptly", "category": "Kolesarske poti", "location": "Moste", "status": "v obravnavi"},
    {"title": "Public transport integration", "description": "Poor connection between modes", "category": "LPP", "location": "Sostro", "status": "odgovorjeno"},
    
    
    {"title": "Tree planting in neighborhood", "description": "More trees needed for shade", "category": "Drevesa, rastje in zelene površine", "location": "Ljubljana Center", "status": "odgovorjeno"},
    {"title": "Recycling bin placement", "description": "More recycling bins needed", "category": "Razno", "location": "Bežigrad", "status": "odgovorjeno"},
    {"title": "Green space maintenance", "description": "Park needs better care", "category": "Parki in zelenice", "location": "Šiška", "status": "odgovorjeno"},
    {"title": "Air quality monitoring", "description": "Install air quality sensors", "category": "Razno", "location": "Vič", "status": "odgovorjeno"},
    {"title": "Water conservation", "description": "Install water-saving devices", "category": "Vodovod", "location": "Moste", "status": "odgovorjeno"},
    {"title": "Solar panel installation", "description": "Solar panels on public buildings", "category": "Razno", "location": "Sostro", "status": "odgovorjeno"},
    {"title": "Bike sharing expansion", "description": "More bike sharing stations", "category": "Kolesarske poti", "location": "Šentvid", "status": "odgovorjeno"},
    {"title": "Community garden creation", "description": "New community garden space", "category": "Parki in zelenice", "location": "Polje", "status": "odgovorjeno"},
    {"title": "Electric vehicle charging", "description": "More EV charging stations", "category": "Razno", "location": "Rožnik", "status": "odgovorjeno"},
    {"title": "Waste reduction program", "description": "Composting facilities needed", "category": "Razno", "location": "Ljubljana Center", "status": "odgovorjeno"},
    {"title": "Bird sanctuary creation", "description": "Protect local bird species", "category": "Drevesa, rastje in zelene površine", "location": "Bežigrad", "status": "odgovorjeno"},
    {"title": "Green roof installation", "description": "Green roofs on buildings", "category": "Razno", "location": "Šiška", "status": "odgovorjeno"},
    {"title": "Water fountain repair", "description": "Drinking fountains not working", "category": "Vodovod", "location": "Vič", "status": "odgovorjeno"},
    {"title": "Native plant restoration", "description": "Restore native vegetation", "category": "Drevesa, rastje in zelene površine", "location": "Moste", "status": "odgovorjeno"},
    {"title": "Energy efficiency program", "description": "LED street lighting", "category": "Ceste", "location": "Sostro", "status": "odgovorjeno"},
    {"title": "Urban beekeeping initiative", "description": "Install beehives in parks", "category": "Drevesa, rastje in zelene površine", "location": "Šentvid", "status": "odgovorjeno"},
    {"title": "Rainwater harvesting", "description": "Collect rainwater for irrigation", "category": "Vodovod", "location": "Polje", "status": "odgovorjeno"},
    {"title": "Green wall installation", "description": "Vertical gardens on buildings", "category": "Drevesa, rastje in zelene površine", "location": "Rožnik", "status": "odgovorjeno"},
    {"title": "Composting program", "description": "Community composting facilities", "category": "Razno", "location": "Ljubljana Center", "status": "odgovorjeno"},
    {"title": "Wildlife corridor creation", "description": "Connect green spaces", "category": "Drevesa, rastje in zelene površine", "location": "Bežigrad", "status": "odgovorjeno"},
    {"title": "Sustainable drainage", "description": "Natural water filtration", "category": "Vodovod", "location": "Šiška", "status": "odgovorjeno"},
    {"title": "Urban forest expansion", "description": "Plant more trees", "category": "Drevesa, rastje in zelene površine", "location": "Vič", "status": "odgovorjeno"},
    {"title": "Renewable energy integration", "description": "Solar and wind power", "category": "Razno", "location": "Moste", "status": "odgovorjeno"},
    {"title": "Green transportation hub", "description": "Eco-friendly transport center", "category": "LPP", "location": "Sostro", "status": "odgovorjeno"},
    {"title": "Biodiversity protection", "description": "Protect local ecosystems", "category": "Drevesa, rastje in zelene površine", "location": "Šentvid", "status": "odgovorjeno"},
    {"title": "Carbon footprint reduction", "description": "City-wide sustainability plan", "category": "Razno", "location": "Polje", "status": "odgovorjeno"},
    {"title": "Green building standards", "description": "Eco-friendly construction", "category": "Razno", "location": "Rožnik", "status": "odgovorjeno"},
    {"title": "Waste sorting education", "description": "Better recycling awareness", "category": "Razno", "location": "Ljubljana Center", "status": "odgovorjeno"},
    {"title": "Urban agriculture", "description": "Community farming spaces", "category": "Drevesa, rastje in zelene površine", "location": "Bežigrad", "status": "odgovorjeno"},
    {"title": "Clean energy transition", "description": "Switch to renewable sources", "category": "Razno", "location": "Šiška", "status": "odgovorjeno"},
    {"title": "Water quality monitoring", "description": "Test local water sources", "category": "Vodovod", "location": "Vič", "status": "odgovorjeno"},
    {"title": "Green infrastructure", "description": "Natural flood protection", "category": "Vodovod", "location": "Moste", "status": "odgovorjeno"},
    {"title": "Sustainable mobility", "description": "Eco-friendly transport options", "category": "Kolesarske poti", "location": "Sostro", "status": "odgovorjeno"},
    {"title": "Environmental education", "description": "Sustainability workshops", "category": "Razno", "location": "Šentvid", "status": "odgovorjeno"},
    {"title": "Green space connectivity", "description": "Connect parks and gardens", "category": "Parki in zelenice", "location": "Polje", "status": "odgovorjeno"},
    {"title": "Climate action plan", "description": "Local climate initiatives", "category": "Razno", "location": "Rožnik", "status": "odgovorjeno"},
    
    
    {"title": "Public art installation", "description": "New sculpture in park", "category": "Kultura", "location": "Ljubljana Center", "status": "odgovorjeno"},
    {"title": "Cultural festival organization", "description": "Annual neighborhood festival", "category": "Kultura", "location": "Bežigrad", "status": "odgovorjeno"},
    {"title": "Library hours extension", "description": "Longer opening hours", "category": "Razno", "location": "Šiška", "status": "odgovorjeno"},
    {"title": "Museum accessibility", "description": "Better access for disabled", "category": "Kultura", "location": "Vič", "status": "odgovorjeno"},
    {"title": "Music venue creation", "description": "New music performance space", "category": "Kultura", "location": "Moste", "status": "odgovorjeno"},
    {"title": "Art workshop space", "description": "Community art studio", "category": "Kultura", "location": "Sostro", "status": "odgovorjeno"},
    {"title": "Historical preservation", "description": "Protect historic buildings", "category": "Kultura", "location": "Šentvid", "status": "odgovorjeno"},
    {"title": "Cultural center renovation", "description": "Update cultural facilities", "category": "Kultura", "location": "Polje", "status": "odgovorjeno"},
    {"title": "Film screening events", "description": "Outdoor movie nights", "category": "Kultura", "location": "Rožnik", "status": "odgovorjeno"},
    {"title": "Theater accessibility", "description": "Better theater access", "category": "Kultura", "location": "Ljubljana Center", "status": "odgovorjeno"},
    {"title": "Street performance permits", "description": "Support local artists", "category": "Kultura", "location": "Bežigrad", "status": "odgovorjeno"},
    {"title": "Cultural heritage tours", "description": "Guided historical walks", "category": "Kultura", "location": "Šiška", "status": "odgovorjeno"},
    {"title": "Art gallery expansion", "description": "More exhibition space", "category": "Kultura", "location": "Vič", "status": "odgovorjeno"},
    {"title": "Music education programs", "description": "Community music classes", "category": "Kultura", "location": "Moste", "status": "odgovorjeno"},
    {"title": "Cultural exchange programs", "description": "International partnerships", "category": "Kultura", "location": "Sostro", "status": "odgovorjeno"},
    {"title": "Public reading spaces", "description": "Outdoor libraries", "category": "Razno", "location": "Šentvid", "status": "odgovorjeno"},
    {"title": "Cultural diversity events", "description": "Celebrate different cultures", "category": "Kultura", "location": "Polje", "status": "odgovorjeno"},
    {"title": "Art in public spaces", "description": "More public art displays", "category": "Kultura", "location": "Rožnik", "status": "odgovorjeno"},
    {"title": "Cultural workshop facilities", "description": "Community learning spaces", "category": "Kultura", "location": "Ljubljana Center", "status": "odgovorjeno"},
    {"title": "Traditional craft preservation", "description": "Support local artisans", "category": "Kultura", "location": "Bežigrad", "status": "odgovorjeno"},
    {"title": "Cultural performance venues", "description": "More performance spaces", "category": "Kultura", "location": "Šiška", "status": "odgovorjeno"},
    
    
    {"title": "School playground upgrade", "description": "Better playground equipment", "category": "Športne površine", "location": "Bežigrad", "status": "odgovorjeno"},
    {"title": "Library book collection", "description": "More books for children", "category": "Razno", "location": "Šiška", "status": "odgovorjeno"},
    {"title": "Computer lab improvement", "description": "New computers for students", "category": "Informatika", "location": "Vič", "status": "odgovorjeno"},
    {"title": "School safety measures", "description": "Better school security", "category": "Razno", "location": "Moste", "status": "odgovorjeno"},
    {"title": "Learning center creation", "description": "New study space", "category": "Razno", "location": "Sostro", "status": "odgovorjeno"},
    {"title": "Adult education programs", "description": "Lifelong learning opportunities", "category": "Razno", "location": "Šentvid", "status": "odgovorjeno"},
    {"title": "Digital literacy classes", "description": "Computer skills training", "category": "Informatika", "location": "Polje", "status": "odgovorjeno"},
    {"title": "Language learning center", "description": "Multilingual education", "category": "Razno", "location": "Rožnik", "status": "odgovorjeno"},
    {"title": "STEM education facilities", "description": "Science and technology labs", "category": "Informatika", "location": "Ljubljana Center", "status": "odgovorjeno"},
    {"title": "Creative arts education", "description": "Art and music programs", "category": "Kultura", "location": "Bežigrad", "status": "odgovorjeno"},
    
    
    {"title": "Sports facility upgrade", "description": "Better gym equipment", "category": "Športne površine", "location": "Šentvid", "status": "odgovorjeno"},
    {"title": "Walking path creation", "description": "New walking trails", "category": "Pešpoti in pločniki", "location": "Polje", "status": "v obravnavi"},
    {"title": "Fitness equipment installation", "description": "Outdoor gym equipment", "category": "Športne površine", "location": "Rožnik", "status": "odgovorjeno"},
    {"title": "Health clinic accessibility", "description": "Better clinic access", "category": "Socialno varstvo in zdravje", "location": "Ljubljana Center", "status": "v obravnavi"},
    {"title": "Mental health support", "description": "Counseling services", "category": "Socialno varstvo in zdravje", "location": "Bežigrad", "status": "odgovorjeno"},
    {"title": "Senior fitness programs", "description": "Exercise classes for elderly", "category": "Socialno varstvo in zdravje", "location": "Šiška", "status": "odgovorjeno"},
    {"title": "Children's health activities", "description": "Youth fitness programs", "category": "Socialno varstvo in zdravje", "location": "Vič", "status": "v obravnavi"},
    {"title": "Wellness center creation", "description": "Holistic health facility", "category": "Socialno varstvo in zdravje", "location": "Moste", "status": "odgovorjeno"},
    {"title": "Nutrition education", "description": "Healthy eating workshops", "category": "Socialno varstvo in zdravje", "location": "Sostro", "status": "v obravnavi"},
    {"title": "Preventive health programs", "description": "Health screening services", "category": "Socialno varstvo in zdravje", "location": "Šentvid", "status": "odgovorjeno"},
    
    
    {"title": "Street lighting improvement", "description": "Better lighting for safety", "category": "Ceste", "location": "Šiška", "status": "v obravnavi"},
    {"title": "Security camera installation", "description": "Cameras for crime prevention", "category": "Javni red in mir", "location": "Vič", "status": "v obravnavi"},
    {"title": "Emergency response time", "description": "Faster emergency services", "category": "Javni red in mir", "location": "Moste", "status": "v obravnavi"},
    {"title": "Police patrol frequency", "description": "More police presence", "category": "Javni red in mir", "location": "Sostro", "status": "v obravnavi"},
    {"title": "Fire safety measures", "description": "Better fire protection", "category": "Javni red in mir", "location": "Šentvid", "status": "v obravnavi"},
    {"title": "Traffic safety improvement", "description": "Safer traffic conditions", "category": "Ceste", "location": "Polje", "status": "v obravnavi"},
    {"title": "Pedestrian safety", "description": "Better pedestrian protection", "category": "Pešpoti in pločniki", "location": "Rožnik", "status": "v obravnavi"},
    {"title": "Bike safety measures", "description": "Safer cycling conditions", "category": "Kolesarske poti", "location": "Ljubljana Center", "status": "v obravnavi"},
    {"title": "School safety upgrade", "description": "Better school security", "category": "Javni red in mir", "location": "Bežigrad", "status": "v obravnavi"},
    {"title": "Public safety awareness", "description": "Safety education programs", "category": "Javni red in mir", "location": "Šiška", "status": "v obravnavi"},
    
    
    {"title": "WiFi in public spaces", "description": "Free WiFi in parks", "category": "Informatika", "location": "Vič", "status": "odgovorjeno"},
    {"title": "Public restroom maintenance", "description": "Better restroom facilities", "category": "Razno", "location": "Moste", "status": "v obravnavi"},
    {"title": "Information kiosk installation", "description": "Tourist information points", "category": "Razno", "location": "Sostro", "status": "odgovorjeno"},
    {"title": "Community notice board", "description": "Public notice boards", "category": "Razno", "location": "Šentvid", "status": "v obravnavi"},
    {"title": "Public seating areas", "description": "More benches and seating", "category": "Parki in zelenice", "location": "Polje", "status": "odgovorjeno"}
]

def generate_random_pobude():
    """Generate random pobude data with realistic Ljubljana problems"""
    with Session(engine) as session:
        
        pobude_to_delete = session.exec(select(Pobuda)).all()
        for pobuda in pobude_to_delete:
            session.delete(pobuda)
        session.commit()
        
        
        for pobuda_data in RANDOM_POBUDE_DATA:
            
            pobuda_data_copy = pobuda_data.copy()
            
            
            if random.random() < 0.3:  
                pobuda_data_copy["status"] = "odgovorjeno"
            else:
                pobuda_data_copy["status"] = "v obravnavi"
            
            
            latitude = 46.0569 + random.uniform(-0.01, 0.01)
            longitude = 14.5058 + random.uniform(-0.01, 0.01)
            
            
            email = f"citizen{random.randint(1, 999)}@ljubljana.si"
            
            pobuda = Pobuda(
                title=pobuda_data_copy["title"],
                description=pobuda_data_copy["description"],
                location=pobuda_data_copy["location"],
                latitude=latitude,
                longitude=longitude,
                email=email,
                category=pobuda_data_copy["category"],
                status=pobuda_data_copy["status"],
                created_at=datetime.utcnow() - timedelta(days=random.randint(1, 180))
            )
            
            
            if pobuda.status == "odgovorjeno":
                pobuda.responded_at = pobuda.created_at + timedelta(days=random.randint(1, 30))
                pobuda.response = f"Thank you for your initiative. We are working on this issue and will provide updates soon."
            
            session.add(pobuda)
        
        session.commit()
        return len(RANDOM_POBUDE_DATA)

router = APIRouter()

@router.post("/api/pobude", response_model=Pobuda)
async def create_pobuda(
    title: str = Form(...),
    description: str = Form(...),
    location: str = Form(...),
    latitude: float = Form(...),
    longitude: float = Form(...),
    email: str = Form(...),
    category: str = Form(default="other"),
    image: Optional[UploadFile] = File(None)
):
    
    image_path = None
    if image:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        file_extension = os.path.splitext(image.filename)[1]
        filename = f"pobuda_{timestamp}{file_extension}"
        file_path = os.path.join(UPLOAD_DIR, filename)
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(image.file, buffer)
        image_path = f"/uploads/{filename}"

    pobuda = Pobuda(
        title=title,
        description=description,
        location=location,
        latitude=latitude,
        longitude=longitude,
        email=email,
        category=category,
        image_path=image_path
    )
    with Session(engine) as session:
        session.add(pobuda)
        session.commit()
        session.refresh(pobuda)
        return pobuda

@router.get("/api/pobude/{pobuda_id}", response_model=Pobuda)
def get_pobuda(pobuda_id: int):
    with Session(engine) as session:
        pobuda = session.get(Pobuda, pobuda_id)
        if not pobuda:
            raise HTTPException(status_code=404, detail="Pobuda not found")
        return pobuda

@router.get("/api/pobude", response_model=List[Pobuda])
def get_pobude(
    limit: Optional[int] = Query(default=None, ge=1, le=100), 
    offset: Optional[int] = Query(default=None, ge=0),
    category: Optional[str] = Query(default=None),
    status: Optional[str] = Query(default=None),
    search: Optional[str] = Query(default=None)
):
    with Session(engine) as session:
        
        statement = select(Pobuda)
        
        
        if category and category != "all":
            statement = statement.where(Pobuda.category == category)
        
        
        if status and status != "all":
            statement = statement.where(Pobuda.status == status)
        
        
        if search and search.strip():
            search_term = f"%{search.strip()}%"
            statement = statement.where(
                (Pobuda.title.ilike(search_term)) |
                (Pobuda.description.ilike(search_term)) |
                (Pobuda.location.ilike(search_term))
            )
        
        
        statement = statement.order_by(Pobuda.created_at.desc())
        
        
        if limit is None and offset is None:
            
            if status and status == "v obravnavi":
                pobude = session.exec(statement).all()
                return pobude
            else:
                
                statement = statement.limit(800)
                pobude = session.exec(statement).all()
                return pobude

        
        effective_limit = limit if limit is not None else 10
        effective_offset = offset if offset is not None else 0
        
        statement = statement.offset(effective_offset).limit(effective_limit)
        pobude = session.exec(statement).all()
        return pobude

@router.put("/api/pobude/{pobuda_id}/respond", response_model=Pobuda)
def respond_to_pobuda(pobuda_id: int, response_data: PobudaResponse):
    with Session(engine) as session:
        pobuda = session.get(Pobuda, pobuda_id)
        if not pobuda:
            raise HTTPException(status_code=404, detail="Pobuda not found")
        pobuda.response = response_data.response
        pobuda.status = "odgovorjeno"
        pobuda.responded_at = datetime.utcnow()
        session.add(pobuda)
        session.commit()
        session.refresh(pobuda)
        return pobuda

@router.get("/api/streets/search", response_model=List[str])
def search_streets(q: str = Query(..., min_length=2), limit: int = Query(20, ge=1, le=50)):
    
    query_lower = q.lower()
    matches = [street for street in LJUBLJANA_STREETS if query_lower in street.lower()]
    return matches[:limit]

@router.post("/api/admin/ai-prioritize")
def ai_prioritize_initiatives(initiatives: List[Pobuda]):
    from .chatgpt_service import prioritize_pobude_list_structured
    
    
    unanswered = [initiative for initiative in initiatives if initiative.status == "v obravnavi"]
    
    if not unanswered:
        return []
    
    
    pobude_for_chatgpt = []
    for initiative in unanswered:
        pobude_for_chatgpt.append({
            "id": initiative.id,
            "naslov": initiative.title,
            "opis": initiative.description,
            "title": initiative.title,  
            "description": initiative.description  
        })
    
    
    prioritized = prioritize_pobude_list_structured(pobude_for_chatgpt)
    
    
    prioritized.sort(key=lambda x: x["nujnost"], reverse=True)
    return prioritized

@router.get("/api/admin/statistics", response_model=Statistics)
def get_statistics():
    with Session(engine) as session:
        pobude = session.exec(select(Pobuda)).all()
        total_pobude = len(pobude)
        pending_pobude = sum(1 for p in pobude if p.status == "v obravnavi")
        responded_pobude = sum(1 for p in pobude if p.status == "odgovorjeno")
        today = datetime.utcnow().date()
        thirty_days_ago = today - timedelta(days=30)
        daily_stats = []
        response_stats = []
        daily_counts = defaultdict(int)
        response_counts = defaultdict(int)
        for pobuda in pobude:
            created_date = pobuda.created_at.date()
            if created_date >= thirty_days_ago:
                daily_counts[created_date] += 1
            if pobuda.responded_at:
                response_date = pobuda.responded_at.date()
                if response_date >= thirty_days_ago:
                    response_counts[response_date] += 1
        for i in range(30):
            date = today - timedelta(days=i)
            daily_stats.append({"date": date.isoformat(), "count": daily_counts[date]})
            response_stats.append({"date": date.isoformat(), "count": response_counts[date]})
        daily_stats.reverse()
        response_stats.reverse()
        return Statistics(
            total_pobude=total_pobude,
            pending_pobude=pending_pobude,
            responded_pobude=responded_pobude,
            daily_stats=daily_stats,
            response_stats=response_stats
        )

@router.post("/api/generate-random-data")
def generate_random_data():
    """Generate random pobude data for testing and demonstration"""
    try:
        count = generate_random_pobude()
        return {"message": f"Generated {count} random pobude with realistic Ljubljana problems", "count": count}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error generating random data: {str(e)}") 